### PR TITLE
select songs updates

### PR DESCRIPTION
**Pull request by johnwang412**
Some instructions on how to fix loading new music.  Take a look and let's talk after you have questions!

Email me if you have any issues.

### CODE REVIEW

**Comment by johnwang412** [comment]
I see you merged my branch into your brcomplte01 branch.  You also have to
merge brcomplte01 branch into master.  You need to create a pull request on
github in order to do that.

Let me know if you have any problems with that?

**Comment by songhaow** [comment]
Yes, I still not fully understand the logic of the git-hub working branches. Therefore, I only studied your updates#8 instructions on git-hub and copied the necessary lines from it.

Yesterday studied your update(#8) and copied/complete the lines into my present program, the graphics part works okay but not the audio part:

The only one thing I am still struggling:

    What is the relationship between:

       this.songBufferInfo = {
 (1)  '02-SW-062018.mp3': {
         'buffer': null,
         'bpm': 95.23,
         'audioSource': null,
       },
       '07-Littlewhiteboat.mp3': {
         'buffer': null,
         'bpm': 123.32,
         'audioSource': null,
       },
     };

(2)  this.track1Name = '02-SW-062018.mp3';
     this.track2Name = '07-Littlewhiteboat.mp3';

(3)    this.songBufferInfo[songName]

When (2) changes, (1) will change automatically?
Or I need to make a code to change it?

If (1) is not changed (3) will still have the original fileName.

I am trying,,,

The several pushes were my practice (for pushing) whenever I modified the code and want you to view my latest version.

Thanks a lot!
________________________________

**Comment by songhaow** [comment]
It didn't let me to complete the pull-request because of some "conflicts".

________________________________

**Comment by johnwang412** [comment]
Do you want to talk tomorrow?  I can go over working with git in some more
detail.  This will become more and more important as you edit bigger and
bigger programs.

I will explain a bit more the difference between this.songBufferInfo AND
this.track1Name now and can talk about it more in person.

this.songBufferInfo is like a filing cabinet where we store information
about any song we have already loaded into our program.  When we open the
filing cabinet, there are many folders.  Each folder represents a song and
has info about that song inside.  Each folder's name is the name of the
song.  When you type this.songBufferInfo['02-SW-062018.mp3'] it basically
means, access the folder named '02-SW-062018.mp3' in the filing cabinet.

If you were at a radio station with this filing cabinet of songs and you
started playing songs from that cabinet, you need to write down somewhere
what song you are playing currently.  this.track1Name is simply the
variable that you write that information in.

this.track1Name has no relationship, therefore, with this.songBufferInfo.
They serve different functions.  When you update one, it does not update
the other.

The way that you want your music player to work is to allow the user to (1)
click the load button and choose a song, (2) have the song be loaded into
the javascript program, (3) select that song as the current one to play,
and (4) play that song.  Step (2) is where you interface with
this.songBufferInfo -- you put the song information you get into the filing
cabinet with other songs.  Step (3) is where you write down that the new
song is the one you wish to start playing.

Hope this helps.

**Comment by songhaow** [comment]
It works now and I am so happy! Programing is fun.

What I did was change the object as the following:

constructor () {
     this.songBufferInfo = [
        {
          trackName: '02-SW-062018.mp3',
          buffer: null,
          bpm: 95.23,
          audioSource: null,
        },
        {
          trackName: '07-Littlewhiteboat.mp3',
          buffer: null,
          bpm: 123.32,
          audioSource: null,
        },
      ];
  }

Therefore the trackNames become dynamic which are identified by index i.

When we talk, you instruct me how to upload into github, because it has conflict and doesn't let me to do the uploading.
________________________________

**Comment by songhaow** [comment]
Now I integrated the song-process.py into songbackend.py program and it can export the json file to the local directory for bpm and beats.

However, for the graphics to work, the json file must be there before the calling. Therefore, two solutions possible:

1) Calling song-process.py from HTML/javascript;

2) Find way to process sound data with javascript codes;

3) Make the bpm and beats an internal data group.

I have trouble with the first option, and I will try the second.

________________________________

**Pull request merged**
